---
deployment:
  tasks:
    # Remove DEPLOYPATH if you are using cPanel Node.js App selector, as it runs from the repo root
    - /usr/bin/npm ci
    - /usr/bin/npm run build
    - touch tmp/restart.txt